---
:LAKE_BTC_API_ACCESSKEY: camilo@instabuyback.com
:LAKE_BTC_API_SECRETKEY: afeb2cb34485ee9a9cdddda3c79ad4951e02860923b7217eda563d7ae4a74fc7
:BITSTAMP_API_ACCESSKEY: eBZAK37zGcj2qa9ZNinJLVnlcJnOc8jG
:BITSTAMP_API_SECRETKEY: FivDNrvRSRjXR5JG6WffztVEW94jLHCC
:BITSTAMP_API_CLIENT_ID: '20287'
:OKCOIN_API_ACCESSKEY: e931ae89-0b8f-48f3-ac21-1ed8de289c84
:OKCOIN_API_SECRETKEY: 51DEB5CB61E3E8142CFCBB3106E5D10A
